### ISSUE TITLE
Add TryEncode/Decode methods

### ISSUE THREAD

**Issue by devhawk** [ssg/SimpleBase#12]
Can you add non-allocating TryEncode/Decode methods that take a Span<byte> buffer to write into + an out int param indicated the number of bytes written. Essentially, have a signature similar to [HashAlgorithm.TryComputeHash](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm.trycomputehash).

Would also be good to expose GetByteCount methods , similar to [Encoding.GetByteCount](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.getbytecount).

**Comment by ssg** [comment]
@devhawk Thanks for the suggestion. Encode returns a string, what do you propose with an output Span, a `Span<byte>` or a `Span<char>`? I wonder about the actual uses cases.

**Comment by devhawk** [comment]
I would propose the signature `bool TryEncode(ReadOnlySpan<byte> input, Span<char> output)`

**Comment by devhawk** [comment]
I want to write something like this, but for base58 encoding

``` csharp
public static bool TryInteropMethodHash(string methodName, out uint value)
{
    Span<byte> asciiMethodName = stackalloc byte[(Encoding.ASCII.GetByteCount(methodName))];
    var getBytesWritten = Encoding.ASCII.GetBytes(methodName, asciiMethodName);
    Debug.Assert(getBytesWritten == asciiMethodName.Length);

    Span<byte> hashBuffer = stackalloc byte[Hash256Size];
    if (_sha256.Value.TryComputeHash(asciiMethodName, hashBuffer, out var hashBytesWritten))
    {
        Debug.Assert(hashBytesWritten == hashBuffer.Length);
        value = BitConverter.ToUInt32(hashBuffer.Slice(0, sizeof(uint)));
        return true;
    }

    value = default;
    return false;
}
```

**Comment by ssg** [comment]
I think `GetByteCount` for Base58.Decode would require the full decoding to be performed, so you'd essentially be doing twice the decoding which might be undesirable for a slow encoding like Base58. 

Would it be okay to get something like  `GetSafeByteCount()` (which can be couple of bytes more than the actual size) and rely on "hashBytesWritten" to process the actual size later? It might be a quite complicated interface but much faster.

**Comment by devhawk** [comment]
Yes, GetSafeByteCount would be fine as long as the actual bytes written count is returned by TryDecode

**Comment by ssg** [comment]
I added these to 3.0.0 release.
