### ISSUE TITLE
ilmerge + anti virus

### ISSUE THREAD

**Issue by ispysoftware** [ssg/SimpleBase#17]
Just a note that projects using ilmerge and bundling SimpleBase.dll are triggering trojan alerts on Kaspersky anti virus.

**Comment by ssg** [comment]
Hi @ispysoftware, do you get the same error when you upload SimpleBase.dll to https://virustotal.com ? What about your ilmerge'd DLL?

**Comment by ispysoftware** [comment]
no, only when it's merged. I've contacted Kaspersky about it and they confirm it's a false positive. Nothing to do about it, just documenting it here in case I forget about it in future :)

**Comment by ssg** [comment]
Awesome, thanks!
