### ISSUE TITLE
Appreciation and Request..

### ISSUE THREAD

**Issue by Xor-el** [ssg/SimpleBase#2]
Hello,
I must say you did an awesome job in this Library,
Well done.

I want to ask though, are there any plans to implement base64 in SimpleBase??
I know it already exists in the net framework but it would be nice to have something similar in pure managed code as part of SimpleBase to have a complete arsenal.
once again well done.

**Comment by ssg** [comment]
Thanks! I have no plans to implement a Base64 encoder/decoder right now since all .NET implementations provide one. There are many other exotic binary to text encoding schemes are around (like MIME, Base36, Base85 etc,) maybe I can add them in the future.

**Comment by Xor-el** [comment]
Ok.
Thanks..
