### ISSUE TITLE
Target netstandard2.0

### ISSUE THREAD

**Issue by cmeeren** [ssg/SimpleBase#20]
Is there any reason this library can't target `netstandard2.0` instead of `netstandard2.1`? The latter would make it compatible with .NET 4.7.

**Comment by ssg** [comment]
Hi @cmeeren, .NET Standard 2.1 includes Span<T> which I use to increase performance which aren't in .NET Standard 2.0. You can use older versions of the library that are .NET Framework compatible if they work for your use cases?

**Comment by cmeeren** [comment]
Yes, that works for me. Thanks for the clarification!
