### ISSUE TITLE
Any plans to strong name the assembly?

### ISSUE THREAD

**Issue by greg-redefined** [ssg/SimpleBase#3]
First, thank you so much for this library.  It really works well and I appreciate all the time and energy you put into it, especially the performance aspect.

Do you have any plans to strong name the assembly?  I think this would help many of us out there.

Cheers!
-Greg

**Comment by ssg** [comment]
Hi Greg, I don't see why not. Would you be willing to submit a pull request for that?

**Comment by ssg** [comment]
Good work Greg! Travis tests are failing but it seems to be related to the build environment. I'll be working on it later. It should be good to go now.

**Comment by greg-redefined** [comment]
Looks like everything is working now with the builds.  Thanks for your patience as I figured this whole Github thing out...  I feel so out of touch... LOL
