### ISSUE TITLE
Dependence on System.Memory?

### ISSUE THREAD

**Issue by NPC** [ssg/SimpleBase#6]
Thanks for the package, trying to figure it out. After adding and calling (a Base32 method), I get a compile error:

> CS0012	The type 'ReadOnlySpan<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Memory, ...'

It does not seem to be a standard assembly (unless I miss something — I'm using ASP.NET, not Core), and I am cautious adding more packages than I have to — especially since it's not mentioned in the readme.

**Comment by ssg** [comment]
Hi @NPC, 

System.Memory is an external package distributed by Microsoft.

What IDE and Framework version are you trying it on so I can reproduce the same problem?

**Comment by NPC** [comment]
Hi @ssg, thanks for responding! It's on Visual Studio Community 2017, with ASP.NET MVC v5.2.3.

**Comment by ssg** [comment]
I resolved this issue in a newer version of the package (1.6.1). You can update it on NuGet and get rid of the compile errors. Thanks for reporting!

**Comment by NPC** [comment]
Great, thank you very much!
