### ISSUE TITLE
Supports for EOS base32 encoding.

### ISSUE THREAD

**Issue by shtse8** [ssg/SimpleBase#8]
I would like to suggest to support EOS base32 encoding alphabet:
```
.12345abcdefghijklmnopqrstuvwxyz
```

https://github.com/EOSIO/eos/blob/master/contracts/eosiolib/types.hpp#L126

**Comment by ssg** [comment]
Would you like to provide a PR with test cases for that?

**Comment by ssg** [comment]
this issue seems to get no interest, closing this.
